[package]
name = "inventorize"
version = "0.0.0"
edition = "2024"
authors = ["FBanna"]
description = "organise parts inventory using a web app and qr code stickers!"

[dependencies]

# server
axum = { version = "0.8.8", features = ["macros", "multipart"]}
axum-login = "0.17.0"
axum-extra = { version = "0.10.1", features = ["erased-json"]}
tower-http = { version = "0.6.2", features = ["cors", "fs", "redirect"] }
password-auth = "1.0.0"
tower = "0.5.2"

# async
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"]}
futures = "0.3"

# serialise/deserialize
serde = { version = "1.0.164", features = ["derive"] }
serde_yaml = "0.9.34"
serde_json = "1.0.149"
jsonschema = "0.44.1"

# typst
typst-pdf = "0.14.2"
typst = "0.14.2"
typst-kit = "0.14.2"

# db
sqlx = { version = "0.8.3", features = ["runtime-tokio-native-tls", "postgres"] }

#async-trait = "0.1.88"

# cli
clap = { version = "4.5.32", features = ["derive", "cargo"]}
reedline = "0.43.0"

# other
time = "0.3.41"

ureq = "3.0.10"
zune-inflate = "0.2.54"
tar = "0.4.44"
image = "0.25.6"
zip = { version = "8.1.0", features = ["_deflate-any"]}

uuid = { version = "1.23.0", features = ["v4", "serde"] }
infer = "0.19.0"

[profile.release]
opt-level = 3
